export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="author" content="Afaq Ahmed"></meta>
      <meta name="title" property="og:title" content="Todo App"></meta>
      <meta property="og:type" content="todo web app"></meta>
      <meta name="image" property="og:image" content="/preview.jpg"></meta>
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
